### ISSUE TITLE
Code issue 

### ISSUE THREAD

**Issue by M-Aitisam** [NeshOfficial/ai-nodejs#2]
Hello,

In this package.js file some issue i this code  this code create many error.  if you  help me to solve this majjor type of error.

class CustomError extends Error {
  constructor(message) {
    super(message);
    this.name = 'CustomError';
  }
}

try {
  // code that might throw an error
  throw new CustomError('This is a custom error');
} catch (error) {
  if (error instanceof CustomError) {
    console.log(`Caught a custom error: ${error.message}`);
  } else {
    console.log(`Caught an unknown error: ${error.message}`);
  }
}

**Comment by Muhammad-Awab** [comment]
this code can resolve the issue


class CustomError extends Error {
  constructor(message) {
    super(message);
    this.name = 'CustomError';
  }
}

try {
  // code that might throw an error
  throw new CustomError('This is a custom error');
} catch (error) {
  if (error instanceof CustomError) {
    // handle the custom error
    console.log(`Caught a custom error: ${error.message}`);
    // you can also add additional logic to resolve the error
    resolveCustomError(error);
  } else {
    // handle unknown errors
    console.log(`Caught an unknown error: ${error.message}`);
  }
}

function resolveCustomError(error) {
  // add logic to resolve the custom error
  // for example, you can retry a failed operation or provide a fallback solution
  console.log('Resolving custom error...');
  // retry a failed operation
  retryOperation();
}

function retryOperation() {
  // add logic to retry a failed operation
  console.log('Retrying failed operation...');
  // if the operation is successful, you can log a success message
  console.log('Operation successful!');
}
